version: 2.1

description: |
  ShellCheck, a static analysis tool for shell scripts https://www.shellcheck.net
  Check all scripts in your repository using `shellcheck` on every commit.

jobs:
  check:
    description: |
      Run shellcheck over any shell scripts in the respository.
      Add this job to any workflow to automatically check any shell scripts
      in your repository.
    parameters:
      path:
        type: string
        default: .
        description: The top-most directory to search for files in.
      pattern:
        type: string
        default: "*.sh"
        description: The file pattern as passed to `find` to locate shell scripts.
    executor: shellcheck
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: find '<< parameters.path >>' -type f -name '<< parameters.pattern >>' | tee /dev/tty | xargs shellcheck --external-sources

executors:
  shellcheck:
    description: |
      This is a docker image that contains the `shellcheck` binary.
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
