version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.1
  shellcheck: circleci/shellcheck@dev:alpha

jobs:

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

add-ssh-keys: &add-ssh-keys
  [run: "apk add git openssh", add_ssh_keys: {fingerprints: ["40:21:b7:d7:fe:ea:dd:80:ca:c8:34:7a:37:b4:b4:d2"]}]

cleanup-git-tag: &cleanup-git-tag
  [run: {when: "always", name: "cleanup tag", command: "git config --global user.email $CIRCLE_USERNAME@users.noreply.github.com && git config --global user.name $CIRCLE_USERNAME && git push --delete origin $CIRCLE_TAG"}]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          orb-name: circleci/shellcheck
          context: orb-publishing
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 40:21:b7:d7:fe:ea:dd:80:ca:c8:34:7a:37:b4:b4:d2
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          cleanup-tags: true
          ssh-fingerprints: 40:21:b7:d7:fe:ea:dd:80:ca:c8:34:7a:37:b4:b4:d2
          tag: master
          requires: [orb-tools/publish-dev]
          filters:
            branches:
              only: master

  integration_test-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      - shellcheck/check:
          name: shellcheck-check_dev
          extract-inline-scripts: true
          filters: *integration-dev_filters

      # triggered by master branch commits
      - shellcheck/check:
          name: shellcheck-check_master
          extract-inline-scripts: true
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/shellcheck
          requires: [shellcheck-check_master]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/shellcheck
          release: minor
          requires: [shellcheck-check_master]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/shellcheck
          release: major
          requires: [shellcheck-check_master]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
